# Generated by Django 3.1.6 on 2021-02-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_contact_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_model',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
